### PR TITLE
Updated requirements files to match the code and added VS python files to gitignore

### PR DESCRIPTION
**Pull request by craigbrett17**
There were several packages (PyDispatcher, Pycurl and Durus) which were needed but weren't in the requirements file

Bit of a pain when I was trying to get started with this project (not as much as the pain of having an old setuptools and it going mental on me, but there you go). Hopefully this'll help anyone new coming along

### CODE REVIEW

**Comment by Oire** [comment]
@craigbrett17, Thanks a lot! Have you tested that? I don't remember why but we preferred to bundle those as binary dependencies in the /dependencies folder. And also, please resolve the conflict as I've removed Twisted and zope.interface, we seem not to use them anymore.

**Comment by craigbrett17** [comment]
@Oire: Yes I've tested it and it pulls in the packages properly. I've only just noticed that those libs are indeed in the distribution folder. Them being there as exes doesn't help Python run the app though and I was getting import errors without them being in the requirements files (and therefore being installed by pip). I can make a fresh clone and send it to you to prove it.

Sure I'll fix it.

**Comment by craigbrett17** [comment]
@Oire: As a better alternative to having these packages in several places (both the distribution folder and requirements), should I raise an issue about it and leave it in your hands?

**Comment by Oire** [comment]
@craigbrett17, thanks a lot, merged! Actually, this dependencies folder was actual when we didn't know about requirements.txt files. And, I guess, there is no way to install WXPython other way besides providing it as a binary.

**Comment by craigbrett17** [comment]
@Oire: That explains it! So the distributions folder for now is for things that have to be installed (WX and Py2Exe I think). Makes sense.

**Pull request merged**
